import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import App from './App'
import './styles.css'
import './styles-products.css'
import './styles-costs.css'
import './styles-orders.css'
import './styles-payments.css'
import './styles-agenda.css'
import './styles-delivery.css'
import './styles-dashboard.css'
import './styles-documents.css'
import './styles-quotes-search.css'
import './styles-reports.css'
import './styles-system.css'
import './styles-shell.css'

createRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>)
